name: abc

on:
  workflow_run:
    workflows: [hello]
    types: [completed]
    branches: [staging, production]

jobs:
  hello:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'abc' }}
    steps:
      - name: firsta
        run: echo ${{ github.ref_name }}
