name: Elixir CI

on: push

env:
  MIX_ENV: test

jobs:
  build:
    if: ${{ false }}
    name: Build and test
    runs-on: ubuntu-20.04
    services:
      db:
        image: postgres:latest
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: saturn_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: view the secrets context
        shell: bash
        run: echo "$SECRETS_CONTEXT"
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.14.3"
          otp-version: "23.2.6"
      - name: Retrieve Cached Dependencies
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            deps
            _build
            priv/plts
          key: mix-${{ runner.os }}-23.2.6-1.14.3-${{ hashFiles('mix.lock') }}

      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test
