name: hello

on: push

jobs:
  first:
    if: github.ref_name == 'staging' || 'productio'
    runs-on: ubuntu-22.04
    steps:
      - name: abcd
        run: echo ${{ github.ref_name }}
  second:
    runs-on: ubuntu-22.04
    steps:
      - name: firsta
        run: echo ${{ github.ref }}
  third:
    if: github.ref_name == ('staging' || 'production')
    runs-on: ubuntu-22.04
    needs: [first, second]
    steps:
      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: abc.yml
