name: hello

on: push

jobs:
  example:
    runs-on: ubuntu-22.04
    steps:
      - name: abcd
        run: echo hello
      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: abc.yml
