name: hello

on: push

jobs:
  first:
    runs-on: ubuntu-22.04
    steps:
      - name: abcd
        run: echo hello
  second:
    runs-on: ubuntu-22.04
    steps:
      - name: firsta
        run: echo ${{ github.event_name }}
  third:
    name: third
    uses: olafbado/elixir-deployment/.github/workflows/abc.yml@staging
    secrets: inherit
